### ISSUE TITLE
feed gives 0 status

### ISSUE THREAD

**Issue by l300lvl** [todevelopers/gnome-shell-extension-rss-feed#1]
just saw this on the review page, and i understand you literally just pushed this, but ive been wanting a feed reader for so long i jumped at the chance to try this. most feeds i have tried work perfectly, but alas:

https://wiki.gnome.org/action/rss_rc/RecentChanges?action=rss_rc&unique=1&ddiffs=1

this one gives 0 when looking at the menu but no errors are returned running gnome-shell --replace from terminal, and i dont have jhbuild for debugging, so i was wondering if you could take a glance? i do see a long list of blank js log callbacks, though.

also, on a side note, sub items would be nice to see in a future release, like the date entry to show the time, but i realize this might be a job for a dedicated feed reader(which i have never used). i know not about the inner working of xml but i do have moderate knowledge of gnome shell.

**Comment by tommy-gun** [comment]
This should be issue with rexml parser library. But it is 3rd side project. I detailed look at this issue later. Thank you for your report.
Some of your feeds shouldn't work because this version doesn't support gzip content.

You should look at this like beta version with only base functionality. It is my first gnome shell extension so I am still learning. But I have some ideas to future releases. For example as you mentioned some extended information like date entry.

**Comment by tommy-gun** [comment]
I have some news for you. Your feed is in RDF format (older RSS 1.0 with different XML structure). I didn't expect that there is such differences.
But now I work on integration of this format to my RSS parser. Next version of extension will have this included.

**Comment by tommy-gun** [comment]
Fixed in version 1.1

**Comment by l300lvl** [comment]
This is exciting to hear. I am grabbing it now to test it out. Thanks for the quick response, it looks like you have done a lot of work!
